### ISSUE TITLE
16 May - label matching with emoji  in PDF

### ISSUE THREAD

**Issue by daijapan** [Kiara-Dev-Team/magic-reminder#9]
you can use emoji or excel cell for the color
🟥　🟨 　🟩

<img width="732" alt="Screenshot 2024-05-16 at 11 58 37" src="https://github.com/Kiara-Dev-Team/magic-reminder/assets/10541717/10059f09-9484-44c1-a42c-2c9f01497def">

**Comment by daijapan** [comment]
quantum concept can be used in future
https://ja.wikipedia.org/wiki/%E9%87%8F%E5%AD%90%E8%89%B2%E5%8A%9B%E5%AD%A6

**Comment by daijapan** [comment]
<img width="739" alt="Screenshot 2024-05-16 at 12 55 17" src="https://github.com/Kiara-Dev-Team/magic-reminder/assets/10541717/ae1fec94-6ef6-447d-b5df-275233f30307">
<img width="738" alt="Screenshot 2024-05-16 at 12 55 23" src="https://github.com/Kiara-Dev-Team/magic-reminder/assets/10541717/3a736b3c-c917-409c-80f4-8ceb4f78bcfc">

**Comment by daijapan** [comment]
- [ ] $10000+ = 🟥 🟥 
- [ ] $1000+ = 🟥
- [ ] $100+  = 🟨

**Comment by daijapan** [comment]
@mayu-kiara done

**Comment by mayu-kiara** [comment]
@daijapan 
ideaの絵文字はどうしますか？

**Comment by daijapan** [comment]
💡 にしましょうか
四角が足りなくなりました

*Dave Ishii, Mathematician *🔢 石井 大輔 数学者

Founder & CEO, Kiara Inc.

We make the better UX in workplace & finance with AI

**Comment by mayu-kiara** [comment]
Done

**Comment by daijapan** [comment]
tks
pls close

*Dave Ishii, Mathematician *🔢 石井 大輔 数学者

Founder & CEO, Kiara Inc.

We make the better UX in workplace & finance with AI
